#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check

test:
  path: /api/test
  controller: App\Controller\ApiController::test